

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    container_name: tarefa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgtarefa
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    