
spring.datasource.url=jdbc:postgresql://localhost:5433/pgtarefa
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.application.name=Listatarefas
